#!/usr/bin/python -u


# Dedicated Control handler script for OpenLieroX
# (http://openlierox.sourceforge.net)

# We're expecting this file to be run from "scripts" dir - that's from rev. 3260 or so
# TODO: NO, we are not expecting this!
# It was only done because this script is buggy and does not work otherwise.

#NOTE: Changes from original:
##Removed Windows-specific checks
##Config is now loaded from scripts directory.

import os, sys, time

import dedicated_control_io as io

# Print Python script errors to external file -
# We should start logging as soon as possible, or we won't get errors about invalid config file

# Add current dir to module search path
sys.path.append( os.getcwd() )
sys.path.append( os.path.dirname(sys.argv[0]) )

cfg_name = "dedicated_config"
if len(sys.argv) > 1:
	cfg_name = sys.argv[1]


exec("import %s as cfg" % cfg_name) #Config file
__builtins__.cfg = cfg # Make it accessible from all modules


#Import handler now. NOT EARLIER because cfg module is needed when importing main handler!
import dedicated_control_handler as hnd


## The game loop ##

hnd.init()

io.messageLog("Dedicated_control started",io.LOG_INFO)

def MainLoop():
	hnd.signalHandler(io.getSignal())


while hnd.gameState != hnd.GAME_QUIT:
	MainLoop()

io.messageLog("Dedicated_control stopped",io.LOG_INFO)
